version: "3.8"
services:
  web:
    build: .
    volumes: 
        - ./site/:/var/www/html
    ports:
        - 80:8080
    extra_hosts: 
        - "teste_host:172.17.0.1"        
  db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./db_data:/docker-entrypoint-initdb.d
        environment: 
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: api_db
        ports:
            - 3306:3306
  cloud-sql-proxy:             
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: /cloud_sql_proxy -instances=nimble-alpha-292623:us-central1:apidb=tcp:0.0.0.0:3306
        ports:
            - 3306:3306

