version: "3.8"
services:
  web:
    build: .
    volumes: 
        - ./site/:/var/www/html
    ports:
        - 80:80
    environment: 
        DB_UPSTREAM: ${DOCKER_GATEWAY_HOST:-host.docker.internal}    
  db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./db_data:/docker-entrypoint-initdb.d
        environment: 
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: api_db
        ports:
            - 3306:3306
