# This is a basic workflow to help you get started with Actions

name: Docker CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow

      # Runs a single command using the runners shell
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # Runs a set of commands using the runners shell
      - name: docker build php
        run: |
          docker build -t php:7.4-apache .
      
      - name: docker build mysql
        run: |
          docker build -t mysql .
      
        - name: Build Docker image
          run: |
            docker build . --tag us.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}
            
        - name: Authenticate into Google Cloud Platform
          uses: GoogleCloudPlatform/nimble-alpha-292623/setup-gcloud@master
          with:
            service_account_email: ${{ secrets. GCLOUD_EMAIL }}
            service_account_key: ${{ secrets.GCLOUD_AUTH }}
  
        - name: Configure Docker to use Google Cloud Platform
          run: "gcloud auth configure-docker --quiet"
  
        - name: Push image to Google Cloud Container Registry
          run: docker push us.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}
  
        - name: Install beta commands and deploy on cloud run
          run: |
            gcloud components install beta --quiet
            gcloud beta run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image us.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }} --project ${{ secrets.GCLOUD_PROJECT }} --region europe-west1 --platform managed
  
      
